// <auto-generated />
using infomerc_site.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace infomercsite.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20180412174545_usuarioAtivoePremium")]
    partial class usuarioAtivoePremium
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("infomerc_site.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Email");

                    b.Property<string>("Interesse");

                    b.Property<string>("Nome");

                    b.Property<bool>("Premium");

                    b.Property<string>("Senha");

                    b.Property<string>("Telefone");

                    b.HasKey("ID");

                    b.ToTable("INFOMERC_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
